server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CValverde92/config-repo.git
          default-label: develop
          search-paths: 'services/{application},services'
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh